source 'http://rubygems.org'

gem 'nokogiri', '1.13.5'
gem 'rspec', '~> 3.8.0'
gem 'cucumber', '~> 3.1.2'
gem 'chromedriver-helper', '~> 2.1', '>= 2.1.1'
gem 'capybara', '~> 3.33'
gem 'site_prism', '~> 3.4', '>= 3.4.2'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
gem 'report_builder', '1.8'
gem 'rubocop', '~> 0.39.0', require: false
